---
name: Run this before a release

on:
  release:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: before a release
        run: |
          echo "Something"
          echo "${GITHUB_REF}" >> README.md
          git add README.md
          git commit -m "chore: updated README with ref ${GITHUB_REF}"
          git push
