---
name: Run this before a release

on:
  release:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: before a release
        run: |
          echo "Something"
          echo "${GITHUB_REF}" >> README.md
          git config user.name 'Gareth Evans'
          git config user.email 'garethjevans@users.noreply.github.com'
          git add README.md
          git commit -m "chore: updated README with ref ${GITHUB_REF}"
          git push
