---
name: Run this for a release

on:
  release:
    types: [published]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: during a release
        run: |
          echo "Something"
