---
name: Do things every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: garethjevans/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
