---
name: Do things every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          env
          cat $GITHUB_EVENT_PATH
